### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:2633

### ISSUE THREAD

**Issue by guigonc** [rogeriochaves/codesearch#1]
Just installed the VS Code extension and I am getting the following error

`Error from Codesearch server, try to reload VS Code. Error: FetchError: request to http://localhost:2633/?q=javascript%20map failed, reason: connect ECONNREFUSED 127.0.0.1:2633`

Tried to reload VS Code several times but the error persists.

Verified port 2633 and actually, it does not seem to have anything running on it

My environment is:
OSX 11.2 (Big Sur)
Python3 3.8.5
VS Code 1.56.2

**Comment by rogeriochaves** [comment]
Thanks for reporting that! Can you try navigating to the extension folder:
```bash
cd ~/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server
```
 Then starting the server
 ```bash
 python3 server.py
 ```
 Which error do you get?

**Comment by guigonc** [comment]
Apparently, it is not finding `numpy` dependency

```
INFO: Initializing hugging face...
Traceback (most recent call last):
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 1, in <module>
    import model
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/model.py", line 5, in <module>
    from nlp import nlp
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/nlp.py", line 13, in <module>
    from transformers import pipeline
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/transformers/dependency_versions_check.py", line 36, in <module>
    from .file_utils import is_tokenizers_available
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/transformers/file_utils.py", line 43, in <module>
    import numpy as np
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/Users/guilhermealmeidagoncalves/.vscode/extensions/rogeriochaves.codesearch-1.0.1/python-server/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/Users/guilhermealmeidagoncalves/opt/anaconda3/bin/python3"
  * The NumPy version is: "1.20.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath' ```

**Comment by rogeriochaves** [comment]
Thanks for reporting it! The issue was that I totally forgot about native bindings! In an attempt to reduce the installation time of the extension, I had packed all python dependencies to ship together, but of course native bindings won't work for every computer this way.

This was fixed by 2f7404bd86288956e2c8ed269a47c35e71bc6890 and published (now at version 1.0.3)

Please try it out and let me know how it goes! (I suggest uninstalling, reloading VS Code then installing again just to be sure)

**Comment by rogeriochaves** [comment]
@guigonc any luck? :)

**Comment by guigonc** [comment]
@rogeriochaves Sorry for the delay.

It worked. Thanks for the support.
